version: "3.8"

services:
  sql-server:
    build:
      context: ./data-base
    ports:
      - "1433:1433"
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sql-server
    volumes:
      - ./data-base/sql-scripts/init-lojadb.sql:/tmp/init-lojadb.sql
      - ./data-base/sql-scripts/init-users-roles.sql:/tmp/init-users-roles.sql
      - ./data-base/sql-scripts/insert-user-roles.sql:/tmp/insert-user-roles.sql
      - ./data-base/init-database.sh:/tmp/init-database.sh
    command: /bin/bash ./tmp/init-database.sh
  angular:
    build:
      context: ./angular
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: always
  api:
    build:
      context: ./webapi
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - mssqltools
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypassword123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__DefaultConnection=Data Source=sql-server;Initial Catalog=DBLoja;User Id=AdmLoja;Password=LojaSenha@247; Trust Server Certificate=True;
    volumes:
      - ./webapi/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
    restart: always
